### ISSUE TITLE
Update x and y

### ISSUE THREAD

**Issue by luizassis** [albhasan/scidbutil#1] opened 2016-09-15 15:09 UTC
Change:

x <- c(-56.325531, -56.325531, -56.239700, -56.239700)
y <- c(-11.623990, -11.676781, -11.676781, -11.623990)

to 

x <- c(-56.239700, -56.325531)
y <- c(-11.623990, -11.676781)

This because spTransform give different results and the last one is the most accurate.

SpatialPoints:
            x        y
[1,] -6133505 -1298400 -----------> x[1] and x[4] must be the same, as well as x[2] and x[3]
[2,] -6124158 -1298400
[3,] -6125322 -1292530
[4,] -6134670 -1292530

SpatialPoints:
            x        y
[1,] -6125322 -1292530
[2,] -6133505 -1298400

I still don't know why but it is better to change this example.

**Comment by albhasan** [comment] 2016-09-15 15:22
Done! I changed the file samples.R

However, I fail to understand the error. Can you provide a complete working script reproducing the error? - Thanks!

**Comment by luizassis** [comment] 2016-09-15 15:37
If you run both examples using the different values of x and y. The results are the following: 

x <- c(-56.325531, -56.325531, -56.239700, -56.239700)
y <- c(-11.623990, -11.676781, -11.676781, -11.623990)

res
    col_id row_id
min  59917  48803
max  59962  48778

---

x <- c(-56.239700, -56.325531)
y <- c(-11.623990, -11.676781)

res
    col_id row_id
min  59922  48803
max  59957  48778

I thought they should provide the same answer (res) but they vary smoothly.

**Comment by albhasan** [comment] 2016-09-15 20:00
I think it is normal because the transformations between spatial reference systems (SRS) introduces slight differences. Besides, the bounding box function for the same geometrical feature can return different values on different SRS. I'm  closing this issue but please open it again if you consider it necessary.

**Closed as completed by albhasan** 2016-09-15 20:00 UTC
